[manager]
border_symbol = " "
border_style = { fg = "#45475A", bg = "#1e1e2e" }
cwd = { fg = "red", bg = "#1e1e2e" }
preview_hovered = { reversed = true, crossed = false, dim = true }
hovered = { reversed = true, crossed = false, dim = true }

[status]
separator_open = " "
separator_close = " "
mode_normal = { fg = "magenta", bg = "#1e1e2e" }
mode_select = { fg = "magenta", bg = "#1e1e2e" }
mode_unset = { fg = "magenta", bg = "#1e1e2e" }

[filetype]
rules = [
	# Orphan symbolic links
	{ name = "*", is = "orphan", fg = "red" },

	# Fallback
	{ name = "*", fg = "magenta", dim=true },
	{ name = "*/", fg = "magenta" }
]

[icon]
prepend_rules = [
	# Icon with a color
	{ name = "*.lua", text = "", fg = "#51a0cf" },
	# You can also use `is` rule, just like `[filetype]` section
	# Orphan symbolic links
	{ name = "*", is = "orphan", text = "", color="yellow" },
]

append_rules = [
	# My fallback icons
	{ name = "*" , text = "" },
	{ name = "*/", text = "" },
]
