[manager] # yazi manager
ratio = [2, 3, 3]
sort_dir_first = true
show_hidden = true


[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = '/home/chilly/Scripts/launch "$@"', desc = "Open" },
]

[open]
rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "video/*", use = "play" },
	{ mime = "image/*", use = "open" },
	{ mime = "application/*", use = "edit" },
]
prepend_rules = [
	{ name = "*.json", use = "edit" },

	# Multiple openers for a single rule
	{ name = "*.html", use = [ "open", "edit" ] },
]
